port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: dashboard

dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: fake-ip
  nameserver:
#    - 202.96.128.86 #电信
    - 119.29.29.29  #腾讯
    - 180.76.76.76  #百度



Proxy:

- { name: "1", type: vmess, server: s1.natfrp.com, port: 6586, uuid: ec04e0f9-2f98-4b0e-bfec-348db869c9f1, alterId: 64, cipher: auto }
- { name: "2", type: vmess, server: s2.natfrp.com, port: 6586, uuid: ec04e0f9-2f98-4b0e-bfec-348db869c9f1, alterId: 64, cipher: auto }
- { name: "3", type: vmess, server: s19.natfrp.com, port: 6586, uuid: ec04e0f9-2f98-4b0e-bfec-348db869c9f1, alterId: 64, cipher: auto }
- { name: "4", type: vmess, server: s25.natfrp.com, port: 6586, uuid: ec04e0f9-2f98-4b0e-bfec-348db869c9f1, alterId: 64, cipher: auto }

Proxy Group:
# url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器


- name: "PROXY"
  type: url-test
  proxies:
    - "1"
    - "2"
    - "3"
    - "4"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

# fallback 通过指定的 URL 测试并选择可用的节点，当 1 故障不可用时自动切换到 2 以此类推
# - name: "Fallback"
#   type: fallback
#   proxies:
#     - "1"
#     - "2"
#     - "3"
#     - "4"
#   url: 'http://www.gstatic.com/generate_204'
#   interval: 300

# load-balance: 负载均衡
# - name: "LoadBalance"
#   type: load-balance
#   proxies:
#     - "1"
#     - "2"
#     - "3"
#     - "4"
#   url: 'http://www.gstatic.com/generate_204'
#   interval: 300



# 规则
Rule:
#绕过onedrive
- DOMAIN-KEYWORD,speedtest,DIRECT
- DOMAIN-KEYWORD,sharepoint,DIRECT
#- DOMAIN,sharepoint.com,DIRECT
#- DOMAIN,*.sharepoint.com,DIRECT

#黑名单模式
#- DOMAIN-KEYWORD,google,PROXY
#- DOMAIN-KEYWORD,youtube,PROXY
#- DOMAIN-KEYWORD,facebook,PROXY
#- DOMAIN-KEYWORD,twitter,PROXY


# 常见广告域名屏蔽
- DOMAIN-KEYWORD,admarvel,REJECT
- DOMAIN-KEYWORD,admaster,REJECT
- DOMAIN-KEYWORD,adsage,REJECT
- DOMAIN-KEYWORD,adsmogo,REJECT
- DOMAIN-KEYWORD,adsrvmedia,REJECT
- DOMAIN-KEYWORD,adwords,REJECT
- DOMAIN-KEYWORD,adservice,REJECT
- DOMAIN-KEYWORD,domob,REJECT
- DOMAIN-KEYWORD,duomeng,REJECT
- DOMAIN-KEYWORD,dwtrack,REJECT
- DOMAIN-KEYWORD,guanggao,REJECT
- DOMAIN-KEYWORD,lianmeng,REJECT
- DOMAIN-SUFFIX,mmstat.com,REJECT
- DOMAIN-KEYWORD,omgmta,REJECT
- DOMAIN-KEYWORD,openx,REJECT
- DOMAIN-KEYWORD,partnerad,REJECT
- DOMAIN-KEYWORD,pingfore,REJECT
- DOMAIN-KEYWORD,supersonicads,REJECT
- DOMAIN-KEYWORD,tracking,REJECT
- DOMAIN-KEYWORD,uedas,REJECT
- DOMAIN-KEYWORD,umeng,REJECT
- DOMAIN-KEYWORD,usage,REJECT
- DOMAIN-KEYWORD,wlmonitor,REJECT
- DOMAIN-KEYWORD,zjtoolbar,REJECT

#绕过CN IP段，其余代理
- GEOIP,CN,DIRECT
- FINAL,PROXY
